Repository cloud-native-toolkit/terraform-gitops-ocp-turbonomic, pull requests merged in 2022-01, with the labels that each got.

#3 nonsens add
  .github/scripts/validate-deploy.sh
  README.md
  charts/charts.helm.k8s.io_xls.yaml
  main.tf
  module.yaml
  scripts/create-yaml.sh
  scripts/deployInstance.sh
  scripts/deployOp.sh
  test/stages/stage1-serviceaccount.tf
  test/stages/stage2-turbo.tf
Labels: enhancement, major

#4 update CR and val check
  .github/scripts/validate-deploy.sh
  main.tf
  module.yaml
  test/stages/stage1-serviceaccount.tf
Labels: patch, chore

#5 Simplifies dependencies and updates module metadata
  .github/workflows/verify.yaml
  README.md
  main.tf
  module.yaml
  test/stages/stage1-cluster.tf
  test/stages/stage1-gitops.tf
  test/stages/stage1-resource-group.tf
  test/stages/stage1-serviceaccount.tf
  test/stages/stage2-turbo.tf
  test/stages/variables.tf
  variables.tf
  version.tf
Labels: bug, patch
